[build]
  # Diretório onde estão os arquivos do site
  publish = "."

[build.environment]
  # Versão do Node.js (opcional, para futuras melhorias)
  NODE_VERSION = "18"

# Configurações para formulários
[build.processing]
  skip_processing = false

# Configurações de formulários e notificações
[[plugins]]
  package = "@netlify/plugin-forms"

# Configuração de notificação por email
[context.production.environment]
  NETLIFY_EMAILS_SECRET = "your-secret-here"

# Redirecionamentos (opcional)
[[redirects]]
  from = "/servicos"
  to = "/servicos.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
